export const ATMO_BANK_TYPES = Object.freeze({
    VALLEY_MIST: 0,
    FOG_POCKET:  1,
    LOW_CLOUD:   2,
    PEAK_CLOUD:  3,
});

export const ATMO_BANK_TYPE_BITS = Object.freeze({
    [ATMO_BANK_TYPES.VALLEY_MIST]: 1 << ATMO_BANK_TYPES.VALLEY_MIST,
    [ATMO_BANK_TYPES.FOG_POCKET]:  1 << ATMO_BANK_TYPES.FOG_POCKET,
    [ATMO_BANK_TYPES.LOW_CLOUD]:   1 << ATMO_BANK_TYPES.LOW_CLOUD,
    [ATMO_BANK_TYPES.PEAK_CLOUD]:  1 << ATMO_BANK_TYPES.PEAK_CLOUD,
});

export const ATMO_BANK_FOG_TYPE_MASK =
    ATMO_BANK_TYPE_BITS[ATMO_BANK_TYPES.VALLEY_MIST] |
    ATMO_BANK_TYPE_BITS[ATMO_BANK_TYPES.FOG_POCKET];

export const ATMO_BANK_CLOUD_TYPE_MASK =
    ATMO_BANK_TYPE_BITS[ATMO_BANK_TYPES.LOW_CLOUD] |
    ATMO_BANK_TYPE_BITS[ATMO_BANK_TYPES.PEAK_CLOUD];

export const ATMO_BANK_ALL_TYPE_MASK =
    ATMO_BANK_FOG_TYPE_MASK |
    ATMO_BANK_CLOUD_TYPE_MASK;

export const ATMO_TYPE_CAPACITY    = 4;
export const ATMO_EMITTER_CAPACITY = 64;
export const ATMO_MAX_PARTICLES    = 256;
export const ATMO_PARTICLE_STRIDE  = 96;
export const ATMO_TYPE_DEF_STRIDE  = 96;
export const ATMO_EMITTER_STRIDE   = 80;
export const ATMO_GLOBALS_SIZE     = 256;
export const ATMO_INDIRECT_SIZE    = 16;
export const ATMO_SCRATCH_SIZE     = 16;
export const ATMO_SCATTER_RULE_CAPACITY = 16;
export const ATMO_SCATTER_RULE_STRIDE   = 80;
export const ATMO_FLAG_ALIVE       = 1;
export const ATMO_WORKGROUP_SIZE   = 64;
export const ATMO_VOLUME_SLICE_COUNT = 3;
export const ATMO_VERTICES_PER_PARTICLE = ATMO_VOLUME_SLICE_COUNT * 6;
