// js/renderer/streamer/LeafMaskBaker.js
//
// One-time bake of procedural leaf alpha masks into a texture array.
// Replaces the per-fragment SDF loops in the leaf shader with a single
// texture sample.
//
// The bake shader runs the IDENTICAL math that buildLeafFragmentShader
// used to run per-pixel-per-frame. Lifting it to a one-time compute
// dispatch is the entire point.
//
// Output texture (rgba8unorm, RES×RES×LAYER_COUNT):
//   R: leaf body alpha
//   G: connector/stem alpha (birch only; 0 for spruce)
//   B, A: reserved
//
// Layer layout:
//   [0 .. BIRCH_MASK_VARIANTS)                       birch cluster variants
//   [BIRCH_MASK_VARIANTS .. +SPRUCE_MASK_VARIANTS)   spruce needle sprays
//
// Quantization note: the procedural path varied continuously with
// vCluster (float 0..1). Baking quantizes to discrete layers. Each
// layer uses centre-of-bin vCluster so floor(vCluster*N) at sample
// time recovers the same integer variant the procedural path would
// have derived. The intra-bin seed drift (vCluster*127.0 in the hash)
// is lost — if 12 birch variants look repetitive in review, raise
// BIRCH_MASK_VARIANTS and re-run; cost is linear in layer count and
// the whole atlas is a few MB.

import { Logger } from '../../config/Logger.js';
import { buildLeafMaskBakeShader } from './shaders/leafMaskBake.wgsl.js';


export const LEAF_MASK_RESOLUTION     = 256;
export const BIRCH_MASK_VARIANTS      = 12;
export const SPRUCE_MASK_VARIANTS     = 8;
export const SPRUCE_MASK_LAYER_OFFSET = BIRCH_MASK_VARIANTS;
export const LEAF_MASK_LAYER_COUNT    = BIRCH_MASK_VARIANTS + SPRUCE_MASK_VARIANTS;

// NEW: separate albedo texture for birch leaves (512×512, generated by PropMaterialFactory)
// The leaf mask atlas keeps its alpha mask role.
// A second texture carries albedo + normal (as separate 2d-array textures).
export const BIRCH_LEAF_ALBEDO_RESOLUTION = 512;
export const BIRCH_LEAF_NORMAL_RESOLUTION = 512;

const BAKE_WORKGROUP_DIM = 8;

export class LeafMaskBaker {
    /**
     * @param {GPUDevice} device
     */
    constructor(device) {
        this.device = device;
        this._texture = null;
        this._view = null;
        this._sampler = null;
        this._initialized = false;
    }

    async initialize() {
        if (this._initialized) return;

        // Needs STORAGE_BINDING for the bake write and TEXTURE_BINDING
        // for runtime sampling. rgba8unorm is on WebGPU's required
        // storage-format list so this is portable.
        this._texture = this.device.createTexture({
            label: 'LeafMask-Atlas',
            size: {
                width:  LEAF_MASK_RESOLUTION,
                height: LEAF_MASK_RESOLUTION,
                depthOrArrayLayers: LEAF_MASK_LAYER_COUNT,
            },
            format: 'rgba8unorm',
            dimension: '2d',
            usage: GPUTextureUsage.STORAGE_BINDING
                 | GPUTextureUsage.TEXTURE_BINDING,
        });

        this._view = this._texture.createView({ dimension: '2d-array' });

        // No mips. The procedural path had no mip-equivalent either
        // (it evaluated the full-res SDF regardless of distance), so
        // this is at worst parity. If shimmer shows up at mid-range
        // in review, mip generation goes here — but that needs a
        // render-pass-based path since storage textures don't get
        // generateMipmap, so deferring until there's a demonstrated
        // need.
        this._sampler = this.device.createSampler({
            label: 'LeafMask-Sampler',
            magFilter: 'linear',
            minFilter: 'linear',
            addressModeU: 'clamp-to-edge',
            addressModeV: 'clamp-to-edge',
        });

        this._bake();

        this._initialized = true;

        const bytes = LEAF_MASK_RESOLUTION * LEAF_MASK_RESOLUTION
                    * LEAF_MASK_LAYER_COUNT * 4;
        Logger.info(
            `[LeafMaskBaker] Baked ${LEAF_MASK_LAYER_COUNT} layers ` +
            `(${BIRCH_MASK_VARIANTS} birch + ${SPRUCE_MASK_VARIANTS} spruce) ` +
            `@ ${LEAF_MASK_RESOLUTION}² = ${(bytes / 1024 / 1024).toFixed(1)}MB`
        );
    }

    _bake() {
        const code = buildLeafMaskBakeShader({
            resolution:     LEAF_MASK_RESOLUTION,
            birchVariants:  BIRCH_MASK_VARIANTS,
            spruceVariants: SPRUCE_MASK_VARIANTS,
            workgroupDim:   BAKE_WORKGROUP_DIM,
        });

        const module = this.device.createShaderModule({
            label: 'LeafMaskBake-SM',
            code,
        });

        const bgl = this.device.createBindGroupLayout({
            label: 'LeafMaskBake-BGL',
            entries: [{
                binding: 0,
                visibility: GPUShaderStage.COMPUTE,
                storageTexture: {
                    access: 'write-only',
                    format: 'rgba8unorm',
                    viewDimension: '2d-array',
                },
            }],
        });

        const pipeline = this.device.createComputePipeline({
            label: 'LeafMaskBake-Pipeline',
            layout: this.device.createPipelineLayout({ bindGroupLayouts: [bgl] }),
            compute: { module, entryPoint: 'main' },
        });

        const bg = this.device.createBindGroup({
            label: 'LeafMaskBake-BG',
            layout: bgl,
            entries: [{ binding: 0, resource: this._view }],
        });

        const encoder = this.device.createCommandEncoder({ label: 'LeafMaskBake-Enc' });
        const pass = encoder.beginComputePass({ label: 'LeafMaskBake' });
        pass.setPipeline(pipeline);
        pass.setBindGroup(0, bg);

        // workgroup_size is (DIM, DIM, 1); Z dispatch = one workgroup-slice
        // per layer, so gid.z == layer index directly.
        const wgXY = Math.ceil(LEAF_MASK_RESOLUTION / BAKE_WORKGROUP_DIM);
        pass.dispatchWorkgroups(wgXY, wgXY, LEAF_MASK_LAYER_COUNT);
        pass.end();

        this.device.queue.submit([encoder.finish()]);
        // No need to await: queue ordering guarantees the bake finishes
        // before any subsequent render pass that samples the texture.
    }

    getTextureView() { return this._view; }
    getSampler()     { return this._sampler; }
    isReady()        { return this._initialized; }

    dispose() {
        this._texture?.destroy();
        this._texture = null;
        this._view = null;
        this._sampler = null;
        this._initialized = false;
    }
}