import { TILE_TYPES } from '../../shared/types.js';
import { TEXTURE_LEVELS } from '../configs/TileConfig.js';
import { sameForAllSeasons, withSeed } from './reusable/shared.js';
import {
  FOREST_DENSE_SINGLE_A,
  FOREST_DENSE_SINGLE_B,
  FOREST_SPARSE_SINGLE_A,
  FOREST_SPARSE_SINGLE_B,
  FOREST_DENSE_MIXED_A,
  FOREST_DENSE_MIXED_B,
  FOREST_SPARSE_MIXED_A,
  FOREST_SPARSE_MIXED_B,
  FOREST_RAINFOREST_A,
  FOREST_RAINFOREST_B,
  FOREST_JUNGLE_A,
  FOREST_JUNGLE_B,
  FOREST_FLOOR_MACRO
} from './reusable/forestFloorTextures.js';

function makeForestFloor(id, name, seedOffset, microA, microB) {
  return {
    id,
    name,
    textures: {
      base: sameForAllSeasons({
        [TEXTURE_LEVELS.MICRO]: [
          withSeed(microA, seedOffset),
          withSeed(microB, seedOffset),
        ],
        [TEXTURE_LEVELS.MACRO]: [FOREST_FLOOR_MACRO],
      }),
    },
  };
}

export const FOREST_FLOOR_TILES = [
  makeForestFloor(TILE_TYPES.FOREST_DENSE_SINGLE_1, 'FOREST_DENSE_SINGLE_1', 10, FOREST_DENSE_SINGLE_A, FOREST_DENSE_SINGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_DENSE_SINGLE_2, 'FOREST_DENSE_SINGLE_2', 20, FOREST_DENSE_SINGLE_A, FOREST_DENSE_SINGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_DENSE_SINGLE_3, 'FOREST_DENSE_SINGLE_3', 30, FOREST_DENSE_SINGLE_A, FOREST_DENSE_SINGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_DENSE_SINGLE_4, 'FOREST_DENSE_SINGLE_4', 40, FOREST_DENSE_SINGLE_A, FOREST_DENSE_SINGLE_B),

  makeForestFloor(TILE_TYPES.FOREST_SPARSE_SINGLE_1, 'FOREST_SPARSE_SINGLE_1', 110, FOREST_SPARSE_SINGLE_A, FOREST_SPARSE_SINGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_SPARSE_SINGLE_2, 'FOREST_SPARSE_SINGLE_2', 120, FOREST_SPARSE_SINGLE_A, FOREST_SPARSE_SINGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_SPARSE_SINGLE_3, 'FOREST_SPARSE_SINGLE_3', 130, FOREST_SPARSE_SINGLE_A, FOREST_SPARSE_SINGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_SPARSE_SINGLE_4, 'FOREST_SPARSE_SINGLE_4', 140, FOREST_SPARSE_SINGLE_A, FOREST_SPARSE_SINGLE_B),

  makeForestFloor(TILE_TYPES.FOREST_DENSE_MIXED_1, 'FOREST_DENSE_MIXED_1', 210, FOREST_DENSE_MIXED_A, FOREST_DENSE_MIXED_B),
  makeForestFloor(TILE_TYPES.FOREST_DENSE_MIXED_2, 'FOREST_DENSE_MIXED_2', 220, FOREST_DENSE_MIXED_A, FOREST_DENSE_MIXED_B),
  makeForestFloor(TILE_TYPES.FOREST_DENSE_MIXED_3, 'FOREST_DENSE_MIXED_3', 230, FOREST_DENSE_MIXED_A, FOREST_DENSE_MIXED_B),
  makeForestFloor(TILE_TYPES.FOREST_DENSE_MIXED_4, 'FOREST_DENSE_MIXED_4', 240, FOREST_DENSE_MIXED_A, FOREST_DENSE_MIXED_B),

  makeForestFloor(TILE_TYPES.FOREST_SPARSE_MIXED_1, 'FOREST_SPARSE_MIXED_1', 310, FOREST_SPARSE_MIXED_A, FOREST_SPARSE_MIXED_B),
  makeForestFloor(TILE_TYPES.FOREST_SPARSE_MIXED_2, 'FOREST_SPARSE_MIXED_2', 320, FOREST_SPARSE_MIXED_A, FOREST_SPARSE_MIXED_B),
  makeForestFloor(TILE_TYPES.FOREST_SPARSE_MIXED_3, 'FOREST_SPARSE_MIXED_3', 330, FOREST_SPARSE_MIXED_A, FOREST_SPARSE_MIXED_B),
  makeForestFloor(TILE_TYPES.FOREST_SPARSE_MIXED_4, 'FOREST_SPARSE_MIXED_4', 340, FOREST_SPARSE_MIXED_A, FOREST_SPARSE_MIXED_B),

  makeForestFloor(TILE_TYPES.FOREST_RAINFOREST_1, 'FOREST_RAINFOREST_1', 410, FOREST_RAINFOREST_A, FOREST_RAINFOREST_B),
  makeForestFloor(TILE_TYPES.FOREST_RAINFOREST_2, 'FOREST_RAINFOREST_2', 420, FOREST_RAINFOREST_A, FOREST_RAINFOREST_B),
  makeForestFloor(TILE_TYPES.FOREST_RAINFOREST_3, 'FOREST_RAINFOREST_3', 430, FOREST_RAINFOREST_A, FOREST_RAINFOREST_B),
  makeForestFloor(TILE_TYPES.FOREST_RAINFOREST_4, 'FOREST_RAINFOREST_4', 440, FOREST_RAINFOREST_A, FOREST_RAINFOREST_B),

  makeForestFloor(TILE_TYPES.FOREST_JUNGLE_1, 'FOREST_JUNGLE_1', 510, FOREST_JUNGLE_A, FOREST_JUNGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_JUNGLE_2, 'FOREST_JUNGLE_2', 520, FOREST_JUNGLE_A, FOREST_JUNGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_JUNGLE_3, 'FOREST_JUNGLE_3', 530, FOREST_JUNGLE_A, FOREST_JUNGLE_B),
  makeForestFloor(TILE_TYPES.FOREST_JUNGLE_4, 'FOREST_JUNGLE_4', 540, FOREST_JUNGLE_A, FOREST_JUNGLE_B),
];

export default FOREST_FLOOR_TILES;
