import { TILE_TYPES } from '../configs/tileTypes.js';
import { TEXTURE_LEVELS } from '../configs/TileConfig.js';
import { sameForAllSeasons, withSeed } from './reusable/shared.js';
import {
  DESERT_DRY_A,
  DESERT_DRY_B,
  DESERT_SEMI_ARID_A,
  DESERT_SEMI_ARID_B,
  DESERT_TREES_DRY_A,
  DESERT_TREES_DRY_B,
  DESERT_TREES_SEMI_ARID_A,
  DESERT_TREES_SEMI_ARID_B,
  DESERT_MACRO
} from './reusable/desertTextures.js';

function makeDesert(id, name, seedOffset, microA, microB) {
  return {
    id,
    name,
    textures: {
      base: sameForAllSeasons({
        [TEXTURE_LEVELS.MICRO]: [
          withSeed(microA, seedOffset),
          withSeed(microB, seedOffset),
        ],
        [TEXTURE_LEVELS.MACRO]: [DESERT_MACRO],
      }),
    },
  };
}

export const DESERT_TILES = [
  makeDesert(TILE_TYPES.DESERT_DRY_1, 'DESERT_DRY_1', 10, DESERT_DRY_A, DESERT_DRY_B),
  makeDesert(TILE_TYPES.DESERT_DRY_2, 'DESERT_DRY_2', 20, DESERT_DRY_A, DESERT_DRY_B),
  makeDesert(TILE_TYPES.DESERT_DRY_3, 'DESERT_DRY_3', 30, DESERT_DRY_A, DESERT_DRY_B),
  makeDesert(TILE_TYPES.DESERT_DRY_4, 'DESERT_DRY_4', 40, DESERT_DRY_A, DESERT_DRY_B),

  makeDesert(TILE_TYPES.DESERT_SEMI_ARID_1, 'DESERT_SEMI_ARID_1', 110, DESERT_SEMI_ARID_A, DESERT_SEMI_ARID_B),
  makeDesert(TILE_TYPES.DESERT_SEMI_ARID_2, 'DESERT_SEMI_ARID_2', 120, DESERT_SEMI_ARID_A, DESERT_SEMI_ARID_B),
  makeDesert(TILE_TYPES.DESERT_SEMI_ARID_3, 'DESERT_SEMI_ARID_3', 130, DESERT_SEMI_ARID_A, DESERT_SEMI_ARID_B),
  makeDesert(TILE_TYPES.DESERT_SEMI_ARID_4, 'DESERT_SEMI_ARID_4', 140, DESERT_SEMI_ARID_A, DESERT_SEMI_ARID_B),

  makeDesert(TILE_TYPES.DESERT_TREES_DRY_1, 'DESERT_TREES_DRY_1', 210, DESERT_TREES_DRY_A, DESERT_TREES_DRY_B),
  makeDesert(TILE_TYPES.DESERT_TREES_DRY_2, 'DESERT_TREES_DRY_2', 220, DESERT_TREES_DRY_A, DESERT_TREES_DRY_B),
  makeDesert(TILE_TYPES.DESERT_TREES_DRY_3, 'DESERT_TREES_DRY_3', 230, DESERT_TREES_DRY_A, DESERT_TREES_DRY_B),
  makeDesert(TILE_TYPES.DESERT_TREES_DRY_4, 'DESERT_TREES_DRY_4', 240, DESERT_TREES_DRY_A, DESERT_TREES_DRY_B),

  makeDesert(TILE_TYPES.DESERT_TREES_SEMI_ARID_1, 'DESERT_TREES_SEMI_ARID_1', 310, DESERT_TREES_SEMI_ARID_A, DESERT_TREES_SEMI_ARID_B),
  makeDesert(TILE_TYPES.DESERT_TREES_SEMI_ARID_2, 'DESERT_TREES_SEMI_ARID_2', 320, DESERT_TREES_SEMI_ARID_A, DESERT_TREES_SEMI_ARID_B),
  makeDesert(TILE_TYPES.DESERT_TREES_SEMI_ARID_3, 'DESERT_TREES_SEMI_ARID_3', 330, DESERT_TREES_SEMI_ARID_A, DESERT_TREES_SEMI_ARID_B),
  makeDesert(TILE_TYPES.DESERT_TREES_SEMI_ARID_4, 'DESERT_TREES_SEMI_ARID_4', 340, DESERT_TREES_SEMI_ARID_A, DESERT_TREES_SEMI_ARID_B),
];

export default DESERT_TILES;
