import { TILE_TYPES } from '../../types.js';
import { TEXTURE_LEVELS } from '../TileConfig.js';
import { sameForAllSeasons, withSeed } from './reusable/shared.js';
import {
  GRASS_SHORT_A,
  GRASS_SHORT_B,
  GRASS_MEDIUM_A,
  GRASS_MEDIUM_B,

  GRASS_TALL_A,
  GRASS_TALL_B,
  GRASS_FLOWER_FIELD_A,
  GRASS_FLOWER_FIELD_B,
  GRASS_MACRO
} from './reusable/grassTextures.js';

function makeGrass(id, name, seedOffset, microA, microB) {
  return {
    id,
    name,
    textures: {
      base: sameForAllSeasons({
        [TEXTURE_LEVELS.MICRO]: [
          withSeed(microA, seedOffset),
          withSeed(microB, seedOffset),
        ],
        [TEXTURE_LEVELS.MACRO]: [GRASS_MACRO],
      }),
    },
  };
}

export const GRASS_TILES = [
  makeGrass(TILE_TYPES.GRASS_SHORT_1, 'GRASS_SHORT_1', 10, GRASS_SHORT_A, GRASS_SHORT_B),
  makeGrass(TILE_TYPES.GRASS_SHORT_2, 'GRASS_SHORT_2', 20, GRASS_SHORT_A, GRASS_SHORT_B),
  makeGrass(TILE_TYPES.GRASS_SHORT_3, 'GRASS_SHORT_3', 30, GRASS_SHORT_A, GRASS_SHORT_B),
  makeGrass(TILE_TYPES.GRASS_SHORT_4, 'GRASS_SHORT_4', 40, GRASS_SHORT_A, GRASS_SHORT_B),

  makeGrass(TILE_TYPES.GRASS_MEDIUM_1, 'GRASS_MEDIUM_1', 110, GRASS_MEDIUM_A, GRASS_MEDIUM_B),
  makeGrass(TILE_TYPES.GRASS_MEDIUM_2, 'GRASS_MEDIUM_2', 120, GRASS_MEDIUM_A, GRASS_MEDIUM_B),
  makeGrass(TILE_TYPES.GRASS_MEDIUM_3, 'GRASS_MEDIUM_3', 130, GRASS_MEDIUM_A, GRASS_MEDIUM_B),
  makeGrass(TILE_TYPES.GRASS_MEDIUM_4, 'GRASS_MEDIUM_4', 140, GRASS_MEDIUM_A, GRASS_MEDIUM_B),

  makeGrass(TILE_TYPES.GRASS_TALL_1, 'GRASS_TALL_1', 210, GRASS_TALL_A, GRASS_TALL_B),
  makeGrass(TILE_TYPES.GRASS_TALL_2, 'GRASS_TALL_2', 220, GRASS_TALL_A, GRASS_TALL_B),
  makeGrass(TILE_TYPES.GRASS_TALL_3, 'GRASS_TALL_3', 230, GRASS_TALL_A, GRASS_TALL_B),
  makeGrass(TILE_TYPES.GRASS_TALL_4, 'GRASS_TALL_4', 240, GRASS_TALL_A, GRASS_TALL_B),

  makeGrass(TILE_TYPES.GRASS_MEADOW_1, 'GRASS_MEADOW_1', 310, GRASS_SHORT_A, GRASS_SHORT_B),
  makeGrass(TILE_TYPES.GRASS_MEADOW_2, 'GRASS_MEADOW_2', 320, GRASS_SHORT_A, GRASS_SHORT_B),
  makeGrass(TILE_TYPES.GRASS_MEADOW_3, 'GRASS_MEADOW_3', 330, GRASS_SHORT_A, GRASS_SHORT_B),
  makeGrass(TILE_TYPES.GRASS_MEADOW_4, 'GRASS_MEADOW_4', 340, GRASS_SHORT_A, GRASS_SHORT_B),

  makeGrass(TILE_TYPES.GRASS_FLOWER_FIELD_1, 'GRASS_FLOWER_FIELD_1', 410, GRASS_FLOWER_FIELD_A, GRASS_FLOWER_FIELD_B),
  makeGrass(TILE_TYPES.GRASS_FLOWER_FIELD_2, 'GRASS_FLOWER_FIELD_2', 420, GRASS_FLOWER_FIELD_A, GRASS_FLOWER_FIELD_B),
  makeGrass(TILE_TYPES.GRASS_FLOWER_FIELD_3, 'GRASS_FLOWER_FIELD_3', 430, GRASS_FLOWER_FIELD_A, GRASS_FLOWER_FIELD_B),
  makeGrass(TILE_TYPES.GRASS_FLOWER_FIELD_4, 'GRASS_FLOWER_FIELD_4', 440, GRASS_FLOWER_FIELD_A, GRASS_FLOWER_FIELD_B),
];

export default GRASS_TILES;
