// js/config/tileTransitionConfig.js

import { TILE_TYPES } from "../types.js";

export const TILE_TRANSITION_RULES = [

    // ── Sand boundaries ───────────────────────────────────────────────────────
    // Sand meeting stone: sedimentary layering — none.
    { from: TILE_TYPES.SAND_COARSE_1, to: TILE_TYPES.GRASS_SHORT_1,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_1, to: TILE_TYPES.GRASS_SHORT_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_1, to: TILE_TYPES.GRASS_SHORT_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_1, to: TILE_TYPES.GRASS_SHORT_4,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },

    { from: TILE_TYPES.SAND_COARSE_2, to: TILE_TYPES.GRASS_SHORT_1,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_2, to: TILE_TYPES.GRASS_SHORT_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_2, to: TILE_TYPES.GRASS_SHORT_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_2, to: TILE_TYPES.GRASS_SHORT_4,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },

    { from: TILE_TYPES.SAND_COARSE_3, to: TILE_TYPES.GRASS_SHORT_1,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_3, to: TILE_TYPES.GRASS_SHORT_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_3, to: TILE_TYPES.GRASS_SHORT_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_3, to: TILE_TYPES.GRASS_SHORT_4,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },

    { from: TILE_TYPES.SAND_COARSE_4, to: TILE_TYPES.GRASS_SHORT_1,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_4, to: TILE_TYPES.GRASS_SHORT_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_4, to: TILE_TYPES.GRASS_SHORT_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_4, to: TILE_TYPES.GRASS_SHORT_4,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },


        // Sand meeting stone: sedimentary layering — none.
        { from: TILE_TYPES.SAND_COARSE_1, to: TILE_TYPES.DIRT_DRY_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
        { from: TILE_TYPES.SAND_COARSE_2, to: TILE_TYPES.DIRT_DRY_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    
        { from: TILE_TYPES.SAND_COARSE_3, to: TILE_TYPES.DIRT_DRY_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
        { from: TILE_TYPES.SAND_COARSE_4, to: TILE_TYPES.DIRT_DRY_2,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    
    // Sand meeting stone: sedimentary layering — none.
    { from: TILE_TYPES.SAND_COARSE_1, to: TILE_TYPES.DIRT_DRY_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_2, to: TILE_TYPES.DIRT_DRY_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },

    { from: TILE_TYPES.SAND_COARSE_3, to: TILE_TYPES.DIRT_DRY_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_4, to: TILE_TYPES.DIRT_DRY_3,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },

    // Sand meeting stone: sedimentary layering — none.
    { from: TILE_TYPES.SAND_COARSE_1, to: TILE_TYPES.DIRT_DRY_4,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_2, to: TILE_TYPES.DIRT_DRY_4,  mode: 'blend_hard', breakStyle: 'none', breakStrength: 0.9 },

    { from: TILE_TYPES.SAND_COARSE_3, to: TILE_TYPES.DIRT_DRY_4,  mode: 'blend_soft', breakStyle: 'none', breakStrength: 0.9 },
    { from: TILE_TYPES.SAND_COARSE_4, to: TILE_TYPES.DIRT_DRY_4,  mode: 'blend_hard', breakStyle: 'none', breakStrength: 0.9 },

    

];

// ── Per-tile layer heights ────────────────────────────────────────────────────
// Used only by step_overlay.  Higher value = this tile sits "above" others
// at blend edges, creating a visible lip.  All values in [0, 1].

export const TILE_LAYER_HEIGHTS = {
    [TILE_TYPES.WATER_1]: 0.00,

    [TILE_TYPES.DIRT_DRY_1]:  0.00,
    [TILE_TYPES.DIRT_DRY_2]:  0.00,
    [TILE_TYPES.DIRT_DRY_3]:  0.00,
    [TILE_TYPES.DIRT_DRY_4]:  0.00,
    [TILE_TYPES.DIRT_LOAM_1]:  0.00,
    [TILE_TYPES.DIRT_LOAM_2]:  0.00,
    [TILE_TYPES.DIRT_LOAM_3]:  0.00,
    [TILE_TYPES.DIRT_LOAM_4]:  0.00,
    [TILE_TYPES.DIRT_CLAY_1]:  0.00,
    [TILE_TYPES.DIRT_CLAY_2]:  0.00,
    [TILE_TYPES.DIRT_CLAY_3]:  0.00,
    [TILE_TYPES.DIRT_CLAY_4]:  0.00,
    [TILE_TYPES.MUD_WET_1]:   0.00,
    [TILE_TYPES.MUD_WET_2]:   0.00,
    [TILE_TYPES.MUD_WET_3]:   0.00,
    [TILE_TYPES.MUD_WET_4]:   0.00,
    [TILE_TYPES.MUD_SILT_1]:   0.00,
    [TILE_TYPES.MUD_SILT_2]:   0.00,
    [TILE_TYPES.MUD_SILT_3]:   0.00,
    [TILE_TYPES.MUD_SILT_4]:   0.00,
    [TILE_TYPES.MUD_PEAT_1]:   0.00,
    [TILE_TYPES.MUD_PEAT_2]:   0.00,
    [TILE_TYPES.MUD_PEAT_3]:   0.00,
    [TILE_TYPES.MUD_PEAT_4]:   0.00,
    [TILE_TYPES.SAND_COARSE_1]:  0.02,
    [TILE_TYPES.SAND_COARSE_2]:  0.02,
    [TILE_TYPES.SAND_COARSE_3]:  0.02,
    [TILE_TYPES.SAND_COARSE_4]:  0.02,
    [TILE_TYPES.SAND_MEDIUM_1]:  0.02,
    [TILE_TYPES.SAND_MEDIUM_2]:  0.02,
    [TILE_TYPES.SAND_MEDIUM_3]:  0.02,
    [TILE_TYPES.SAND_MEDIUM_4]:  0.02,
    [TILE_TYPES.SAND_FINE_1]:    0.02,
    [TILE_TYPES.SAND_FINE_2]:    0.02,
    [TILE_TYPES.SAND_FINE_3]:    0.02,
    [TILE_TYPES.SAND_FINE_4]:    0.02,

    [TILE_TYPES.ROCK_OUTCROP_1]:  0.10,
    [TILE_TYPES.ROCK_OUTCROP_2]:  0.10,
    [TILE_TYPES.ROCK_OUTCROP_3]:  0.10,
    [TILE_TYPES.ROCK_OUTCROP_4]:  0.10,
    [TILE_TYPES.ROCK_SLAB_1]:     0.10,
    [TILE_TYPES.ROCK_SLAB_2]:     0.10,
    [TILE_TYPES.ROCK_SLAB_3]:     0.10,
    [TILE_TYPES.ROCK_SLAB_4]:     0.10,
    [TILE_TYPES.ROCK_BOULDER_1]:  0.10,
    [TILE_TYPES.ROCK_BOULDER_2]:  0.10,
    [TILE_TYPES.ROCK_BOULDER_3]:  0.10,
    [TILE_TYPES.ROCK_BOULDER_4]:  0.10,

    [TILE_TYPES.GRASS_SHORT_1]:        0.08,
    [TILE_TYPES.GRASS_SHORT_2]:        0.08,
    [TILE_TYPES.GRASS_SHORT_3]:        0.08,
    [TILE_TYPES.GRASS_SHORT_4]:        0.08,
    [TILE_TYPES.GRASS_MEDIUM_1]:       0.08,
    [TILE_TYPES.GRASS_MEDIUM_2]:       0.08,
    [TILE_TYPES.GRASS_MEDIUM_3]:       0.08,
    [TILE_TYPES.GRASS_MEDIUM_4]:       0.08,
    [TILE_TYPES.GRASS_TALL_1]:         0.08,
    [TILE_TYPES.GRASS_TALL_2]:         0.08,
    [TILE_TYPES.GRASS_TALL_3]:         0.08,
    [TILE_TYPES.GRASS_TALL_4]:         0.08,
    [TILE_TYPES.GRASS_MEADOW_1]:       0.08,
    [TILE_TYPES.GRASS_MEADOW_2]:       0.08,
    [TILE_TYPES.GRASS_MEADOW_3]:       0.08,
    [TILE_TYPES.GRASS_MEADOW_4]:       0.08,
    [TILE_TYPES.GRASS_FLOWER_FIELD_1]: 0.08,
    [TILE_TYPES.GRASS_FLOWER_FIELD_2]: 0.08,
    [TILE_TYPES.GRASS_FLOWER_FIELD_3]: 0.08,
    [TILE_TYPES.GRASS_FLOWER_FIELD_4]: 0.08,
    [TILE_TYPES.FOREST_DENSE_SINGLE_1]: 0.06,
    [TILE_TYPES.FOREST_DENSE_SINGLE_2]: 0.06,
    [TILE_TYPES.FOREST_DENSE_SINGLE_3]: 0.06,
    [TILE_TYPES.FOREST_DENSE_SINGLE_4]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_SINGLE_1]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_SINGLE_2]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_SINGLE_3]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_SINGLE_4]: 0.06,
    [TILE_TYPES.FOREST_DENSE_MIXED_1]: 0.06,
    [TILE_TYPES.FOREST_DENSE_MIXED_2]: 0.06,
    [TILE_TYPES.FOREST_DENSE_MIXED_3]: 0.06,
    [TILE_TYPES.FOREST_DENSE_MIXED_4]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_MIXED_1]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_MIXED_2]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_MIXED_3]: 0.06,
    [TILE_TYPES.FOREST_SPARSE_MIXED_4]: 0.06,
    [TILE_TYPES.FOREST_RAINFOREST_1]: 0.06,
    [TILE_TYPES.FOREST_RAINFOREST_2]: 0.06,
    [TILE_TYPES.FOREST_RAINFOREST_3]: 0.06,
    [TILE_TYPES.FOREST_RAINFOREST_4]: 0.06,
    [TILE_TYPES.FOREST_JUNGLE_1]: 0.06,
    [TILE_TYPES.FOREST_JUNGLE_2]: 0.06,
    [TILE_TYPES.FOREST_JUNGLE_3]: 0.06,
    [TILE_TYPES.FOREST_JUNGLE_4]: 0.06,
    [TILE_TYPES.SWAMP_MARSH_1]:     0.04,
    [TILE_TYPES.SWAMP_MARSH_2]:     0.04,
    [TILE_TYPES.SWAMP_MARSH_3]:     0.04,
    [TILE_TYPES.SWAMP_MARSH_4]:     0.04,
    [TILE_TYPES.SWAMP_BOG_1]:       0.04,
    [TILE_TYPES.SWAMP_BOG_2]:       0.04,
    [TILE_TYPES.SWAMP_BOG_3]:       0.04,
    [TILE_TYPES.SWAMP_BOG_4]:       0.04,
    [TILE_TYPES.SWAMP_MANGROVE_1]:  0.04,
    [TILE_TYPES.SWAMP_MANGROVE_2]:  0.04,
    [TILE_TYPES.SWAMP_MANGROVE_3]:  0.04,
    [TILE_TYPES.SWAMP_MANGROVE_4]:  0.04,

    [TILE_TYPES.TUNDRA_BARREN_1]: 0.03,
    [TILE_TYPES.TUNDRA_BARREN_2]: 0.03,
    [TILE_TYPES.TUNDRA_BARREN_3]: 0.03,
    [TILE_TYPES.TUNDRA_BARREN_4]: 0.03,
    [TILE_TYPES.TUNDRA_LICHEN_1]: 0.03,
    [TILE_TYPES.TUNDRA_LICHEN_2]: 0.03,
    [TILE_TYPES.TUNDRA_LICHEN_3]: 0.03,
    [TILE_TYPES.TUNDRA_LICHEN_4]: 0.03,
    [TILE_TYPES.TUNDRA_MOSS_1]:   0.03,
    [TILE_TYPES.TUNDRA_MOSS_2]:   0.03,
    [TILE_TYPES.TUNDRA_MOSS_3]:   0.03,
    [TILE_TYPES.TUNDRA_MOSS_4]:   0.03,
    [TILE_TYPES.SNOW_FRESH_1]:    0.07,
    [TILE_TYPES.SNOW_FRESH_2]:    0.07,
    [TILE_TYPES.SNOW_FRESH_3]:    0.07,
    [TILE_TYPES.SNOW_FRESH_4]:    0.07,
    [TILE_TYPES.SNOW_PACK_1]:     0.07,
    [TILE_TYPES.SNOW_PACK_2]:     0.07,
    [TILE_TYPES.SNOW_PACK_3]:     0.07,
    [TILE_TYPES.SNOW_PACK_4]:     0.07,
    [TILE_TYPES.SNOW_ICE_1]:      0.07,
    [TILE_TYPES.SNOW_ICE_2]:      0.07,
    [TILE_TYPES.SNOW_ICE_3]:      0.07,
    [TILE_TYPES.SNOW_ICE_4]:      0.07,

    [TILE_TYPES.DESERT_DRY_1]: 0.02,
    [TILE_TYPES.DESERT_DRY_2]: 0.02,
    [TILE_TYPES.DESERT_DRY_3]: 0.02,
    [TILE_TYPES.DESERT_DRY_4]: 0.02,
    [TILE_TYPES.DESERT_SEMI_ARID_1]: 0.02,
    [TILE_TYPES.DESERT_SEMI_ARID_2]: 0.02,
    [TILE_TYPES.DESERT_SEMI_ARID_3]: 0.02,
    [TILE_TYPES.DESERT_SEMI_ARID_4]: 0.02,
    [TILE_TYPES.DESERT_TREES_DRY_1]: 0.02,
    [TILE_TYPES.DESERT_TREES_DRY_2]: 0.02,
    [TILE_TYPES.DESERT_TREES_DRY_3]: 0.02,
    [TILE_TYPES.DESERT_TREES_DRY_4]: 0.02,
    [TILE_TYPES.DESERT_TREES_SEMI_ARID_1]: 0.02,
    [TILE_TYPES.DESERT_TREES_SEMI_ARID_2]: 0.02,
    [TILE_TYPES.DESERT_TREES_SEMI_ARID_3]: 0.02,
    [TILE_TYPES.DESERT_TREES_SEMI_ARID_4]: 0.02,

    [TILE_TYPES.VOLCANIC_BASALT_1]:   0.9,
    [TILE_TYPES.VOLCANIC_BASALT_2]:   0.9,
    [TILE_TYPES.VOLCANIC_BASALT_3]:   0.9,
    [TILE_TYPES.VOLCANIC_BASALT_4]:   0.9,
    [TILE_TYPES.VOLCANIC_ASH_1]:      0.9,
    [TILE_TYPES.VOLCANIC_ASH_2]:      0.9,
    [TILE_TYPES.VOLCANIC_ASH_3]:      0.9,
    [TILE_TYPES.VOLCANIC_ASH_4]:      0.9,
    [TILE_TYPES.VOLCANIC_OBSIDIAN_1]: 0.9,
    [TILE_TYPES.VOLCANIC_OBSIDIAN_2]: 0.9,
    [TILE_TYPES.VOLCANIC_OBSIDIAN_3]: 0.9,
    [TILE_TYPES.VOLCANIC_OBSIDIAN_4]: 0.9,
};
